sudo: required
services:
    - docker

before_install:
    - docker build -t umbongo/docker-complex -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true umbongo/docker-complex npm test

after_success:
    - docker build -t tomconga/multi-client ./client
    - docker build -t tomconga/multi-nginx ./nginx
    - docker build -t tomconga/multi-server ./server
    - docker build -t tomconga/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push tomconga/multi-client:1.1
    - docker push tomconga/multi-nginx:1.1
    - docker push tomconga/multi-server:1.1
    - docker push tomconga/multi-worker:1.1

# deploy:
#     provider: elasticbeanstalk
#     region: ap-southeast-2
#     app: multi-docker
#     env: multiDocker-env
#     bucket_name: elasticbeanstalk-ap-southeast-2-322727971931
#     bucket_path: docker-multi
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY